[parity]
# Custom chain
chain = "/home/parity/.local/share/io.parity.ethereum/chain.json"
# Blockchain and settings will be stored in ./.
base_path = "./"

[rpc]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
# Allows Cross-Origin Requests from domain 'all'.
cors = ["all"]
