name: Extract vars from file
description: 'Read the files from env-vars folder and massage to fit the input for google-github-actions/deploy-cloud-functions'
inputs:
  vars_file:
    description: variable file to ingest
    required: true

runs:
  using: composite
  steps:
      - name: set env vars for Gfunction deploy
        shell: bash
        id: set_env
        run: |
          VARS_COMMA=$(cat ${{ inputs.vars_file }} | paste -s -d, -)
          echo "function_vars=$VARS_COMMA" >> $GITHUB_OUTPUT