name: "Deploy all apps"
on:
  # Allow this wofkflow as a universal "deployer" to 
  # call from other workflows.
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  app:
    name: webapp
    uses: ./.github/workflows/centrifuge-app.yml
    secrets: inherit
    with:
      deploy_env: ${{ inputs.environment}}


  pinning:
    name: pinning
    uses:  ./.github/workflows/pinning-api.yml
    secrets: inherit
    with:
      deploy_env: ${{ inputs.environment }}


  onboarding:
    name: onboarding
    uses: ./.github/workflows/onboarding-api.yml
    secrets: inherit
    with:
      deploy_env: ${{ inputs.environment}}

  faucet:
    if: ${{ inputs.environment == 'demo'  || inputs.environment == 'development' }}
    name: faucet
    uses: ./.github/workflows/faucet-api.yml
    secrets: inherit
    with:
      deploy_env: ${{ inputs.environment}}