import { altairYellow, grayScale, yellowScale } from './colors'

const statusDefault = grayScale[500]
const statusInfo = '#006ef5'
const statusOk = '#74B634'
const statusWarning = '#a86500'
const statusCritical = '#d43F2b'
const statusPromote = '#f81071'

const darkColors = {
  textPrimary: 'white',
  textSecondary: grayScale[500],
  textDisabled: grayScale[500],
  textInverted: 'black',

  backgroundPrimary: 'black',
  backgroundSecondary: grayScale[900],
  backgroundTertiary: grayScale[900],
  backgroundAccentPrimary: grayScale[900],
  backgroundAccentSecondary: grayScale[900],
  backgroundPage: 'black',
  backgroundInput: grayScale[900],
  backgroundThumbnail: grayScale[300],
  backgroundInverted: grayScale[100],

  borderPrimary: grayScale[800],
  borderSecondary: grayScale[900],

  statusDefault,
  statusInfo,
  statusOk,
  statusWarning,
  statusCritical,
  statusPromote,
  statusDefaultBg: 'transparent',
  statusInfoBg: 'transparent',
  statusOkBg: 'transparent',
  statusWarningBg: 'transparent',
  statusCriticalBg: 'transparent',
  statusPromoteBg: 'transparent',

  backgroundButtonPrimary: altairYellow,
  backgroundButtonPrimaryFocus: altairYellow,
  backgroundButtonPrimaryHover: 'white',
  backgroundButtonPrimaryPressed: 'white',
  backgroundButtonPrimaryDisabled: grayScale[500],
  textButtonPrimary: 'black',
  textButtonPrimaryFocus: 'black',
  textButtonPrimaryHover: 'black',
  textButtonPrimaryPressed: 'black',
  textButtonPrimaryDisabled: 'white',
  borderButtonPrimary: altairYellow,
  borderButtonPrimaryFocus: 'white',
  borderButtonPrimaryHover: 'white',
  borderButtonPrimaryPressed: 'white',
  borderButtonPrimaryDisabled: grayScale[500],
  shadowButtonPrimary: altairYellow,

  backgroundButtonSecondary: 'transparent',
  backgroundButtonSecondaryFocus: 'transparent',
  backgroundButtonSecondaryHover: 'black',
  backgroundButtonSecondaryPressed: 'black',
  backgroundButtonSecondaryDisabled: 'transparent',
  textButtonSecondary: 'white',
  textButtonSecondaryFocus: 'white',
  textButtonSecondaryHover: 'white',
  textButtonSecondaryPressed: 'white',
  textButtonSecondaryDisabled: grayScale[500],
  borderButtonSecondary: grayScale[500],
  borderButtonSecondaryFocus: 'white',
  borderButtonSecondaryHover: grayScale[500],
  borderButtonSecondaryPressed: 'white',
  borderButtonSecondaryDisabled: grayScale[500],
  shadowButtonSecondary: 'white',

  backgroundButtonTertiary: 'transparent',
  backgroundButtonTertiaryFocus: 'transparent',
  backgroundButtonTertiaryHover: yellowScale[800],
  backgroundButtonTertiaryPressed: yellowScale[800],
  backgroundButtonTertiaryDisabled: 'transparent',
  textButtonTertiary: 'white',
  textButtonTertiaryFocus: yellowScale[500],
  textButtonTertiaryHover: yellowScale[500],
  textButtonTertiaryPressed: yellowScale[500],
  textButtonTertiaryDisabled: grayScale[500],
  borderButtonTertiary: 'transparent',
  borderButtonTertiaryFocus: 'transparent',
  borderButtonTertiaryHover: 'transparent',
  borderButtonTertiaryPressed: yellowScale[500],
  borderButtonTertiaryDisabled: 'transparent',

  backgroundButtonInverted: 'transparent',
  backgroundButtonInvertedFocus: 'transparent',
  backgroundButtonInvertedHover: 'black',
  backgroundButtonInvertedPressed: 'black',
  backgroundButtonInvertedDisabled: 'transparent',
  textButtonInverted: 'white',
  textButtonInvertedFocus: 'white',
  textButtonInvertedHover: 'white',
  textButtonInvertedPressed: 'white',
  textButtonInvertedDisabled: grayScale[500],
  borderButtonInverted: grayScale[500],
  borderButtonInvertedFocus: 'white',
  borderButtonInvertedHover: grayScale[500],
  borderButtonInvertedPressed: 'white',
  borderButtonInvertedDisabled: grayScale[500],
  shadowButtonInverted: 'white',
}

export const modeDark = {
  colors: darkColors,
}
