[build]
  base = "nft-studio"
  command = "yarn build:all"
  publish = "build"
  environment = { NETLIFY_USE_YARN = "true" }
  functions = "functions"

[dev]
  command = "yarn start:app"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false