name: Extract vars from file
description: 'Read the files from env-vars folder and massage to fit the input for google-github-actions/deploy-cloud-functions'
inputs:
  app_name:
    description: app name to guess the folder for the vars
    required: true
  deploy_env:
    description: environment being deployed
    required: true  

runs:
  using: composite
  steps:
      - name: set secrets for Gfunction deploy
        shell: bash
        id: set_secrets
        run: |
          if ${{ inputs.deploy_env == 'production'}}; then
            FILE=${{ inputs.app_name }}/env-vars/prod.secrets
          else
            FILE=${{ inputs.app_name }}/env-vars/dev.secrets
          fi
          delimiter="$(openssl rand -hex 8)"
          # Add a new line at the end if not already there:
          sed -i -e '$a\' $FILE 
          echo "function_secrets<<${delimiter}" >> $GITHUB_OUTPUT
          cat $FILE >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
