version: '3'

volumes:
  ipfs:
    labels: 
      - "${PROJECT}=ipfs"
  data:
    labels: 
      - "${PROJECT}=data"

services:
  parity:
    image: parity/parity:v2.7.2-stable
    container_name: parity
    user: "1000:1000"
    volumes: 
      - ./parity/chain.json:/home/parity/.local/share/io.parity.ethereum/chain.json
      - ./parity/config.toml:/home/parity/.local/share/io.parity.ethereum/config.toml
    command: --config /home/parity/.local/share/io.parity.ethereum/config.toml
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp

  db:
    image: postgres:12.2-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs:/data/ipfs

  graph:
    image: graphprotocol/graph-node:v0.21.0
    container_name: graph
    depends_on:
      - db
      - ipfs
      - parity
    ports:
      - "8020:8020"
      - "8000:8000"
    environment:
      - ethereum=${ETH_NETWORK}:http://parity:8545
      - ipfs=ipfs:5001
      - postgres_db=${POSTGRES_DB}
      - postgres_host=db
      - postgres_pass=${POSTGRES_PASSWORD}
      - postgres_user=${POSTGRES_USER}
      - postgres_port=5432
      - GRAPH_ALLOW_NON_DETERMINISTIC_IPFS="true"
      - GRAPH_ETH_CALL_BY_NUMBER="true"
      - GRAPH_LOG=info
      - GRAPH_IPFS_TIMEOUT=12000

  contracts:
    build:
      context: ./contracts
    container_name: contracts
    depends_on:
      - parity
    environment:
      - ETH_RPC_URL=http://parity:8545
      - ETH_KEYSTORE=/app/keystore
      - ETH_PASSWORD=/app/dev-password
      - ETH_FROM=${ETH_FROM}
      - ETH_GAS=${ETH_GAS}
      - ETH_PRIVATE_KEY=${ETH_ADMIN_PRIVATE_KEY}
      - POOL_ID=${POOL_ID}
      - IPFS_METADATA=${IPFS_METADATA}
      - IPFS_ROOT=${IPFS_ROOT}
      - GIT_COMMIT_TINLAKE_PROXY=767ef0b
      - GIT_COMMIT_TINLAKE_POOLS_CLI=9d6f7f6
      - GIT_COMMIT_TINLAKE_CLAIM_RAD=6dc0fb8
      - GIT_COMMIT_TINLAKE_ACTIONS=acf08fe
      - GIT_COMMIT_MULTICALL=e0c7d9
      - GIT_COMMIT_ETHEREUM_CONTRACTS=e595582
      - GIT_COMMIT_PRIVACY_ENABLED_ERC721=7b20dcf
      - GIT_COMMIT_TINLAKE_DEPLOY=4ef38c5
    command: ./deploy.sh

  subgraph:
    build:
      context: subgraph
      args: 
        NETWORK_NAME: ${ETH_NETWORK}
        GIT_COMMIT_TINLAKE_SUBGRAPH: e585cbc
    container_name: subgraph
    depends_on:
      - ipfs
      - graph
    environment:
      - GRAPH_HOST=http://graph
      - IPFS_HOST=http://ipfs:5001
      - PROJECT=${PROJECT}
    command: "./deploy.sh"

  tinlake-ui:
    build:
      context: ../tinlake-ui/docker
    container_name: tinlake-ui
    environment:
      NEXT_PUBLIC_CENTRIFUGE_CHAIN_URL=wss://fullnode.centrifuge.io
      NEXT_PUBLIC_CLAIM_CFG_CONTRACT_ADDRESS=0x1cA3B2E7FfCAF83d9228a64e4726402B1d5CC054
      NEXT_PUBLIC_ENV=PROD
      NEXT_PUBLIC_ETHERSCAN_URL=https://etherscan.io
      NEXT_PUBLIC_FEATURE_FLAG_NEW_ONBOARDING=0x4B6CA198d257D755A5275648D471FE09931b764A,0xdB3bC9fB1893222d266762e9fF857EB74D75c7D6,0xfc2950dD337ca8496C18dfc0256Fb905A7E7E5c6,0x53b2d22d07E069a3b132BfeaaD275b10273d381E,0x0CED6166873038Ac0cc688e7E6d19E2cBE251Bf0,0x4cA805cE8EcE2E63FfC1F9f8F2731D3F48DF89Df,0x82B8617A16e388256617FeBBa1826093401a3fE5,0x560Ac248ce28972083B718778EEb0dbC2DE55740,0x3d167bd08f762FD391694c67B5e6aF0868c45538
      NEXT_PUBLIC_INFURA_KEY=bf808e7d3d924fbeb74672d9341d0550
      NEXT_PUBLIC_IPFS_GATEWAY=https://cloudflare-ipfs.com/ipfs/
      NEXT_PUBLIC_MULTICALL_CONTRACT_ADDRESS=0xeefba1e63905ef1d7acba5a8513c70307c1ce441
      NEXT_PUBLIC_ONBOARD_API_HOST=https://onboard-api.centrifuge.io/
      NEXT_PUBLIC_POOL_REGISTRY=0xddf1c516cf87126c6c610b52fd8d609e67fb6033
      NEXT_PUBLIC_POOLS_CONFIG=mainnetProduction
      NEXT_PUBLIC_POOLS_IPFS_HASH_OVERRIDE=QmcbkeM57fGvBNt5NAe7N3UguDd2cVVBNZ2xFoTijnEyFq
      NEXT_PUBLIC_PORTIS_KEY=bc9e2922-2ebd-4e2b-86f6-7c7855bdf07f
      NEXT_PUBLIC_REWARDS_TREE_URL=https://storage.googleapis.com/rad-rewards-trees-mainnet-production/latest.json
      NEXT_PUBLIC_RPC_URL=https://mainnet.infura.io/v3/ed5e0e19bcbc427cbf8f661736d44516
      NEXT_PUBLIC_TINLAKE_DATA_BACKEND_URL=https://thegraph.centrifuge.io/subgraphs/name/centrifuge/tinlake
      NEXT_PUBLIC_TRANSACTION_TIMEOUT=3600
    command: "./deploy.sh"
