export const RESTRICTED_COUNTRY_CODES = {
  by: 'Belarus',
  cd: 'Congo, Dem. Republic',
  cu: 'Cuba',
  iq: 'Iraq',
  ir: 'Iran',
  kp: 'North Korea',
  ly: 'Libya',
  ni: 'Nicaragua',
  ru: 'Russia',
  sd: 'Sudan',
  so: 'Somalia',
  sy: 'Syria',
  ua: 'Ukraine',
  ve: 'Venezuela',
  zw: 'Zimbabwe',
}
