export const RESTRICTED_COUNTRY_CODES = {
  by: 'Belarus',
  cd: 'Congo, Dem. Republic',
  cu: 'Cuba',
  iq: 'Iraq',
  ir: 'Iran',
  kp: 'North Korea',
  ly: 'Libya',
  ni: 'Nicaragua',
  ru: 'Russia',
  sd: 'Sudan',
  so: 'Somalia',
  sy: 'Syria',
  ua: 'Ukraine',
  ve: 'Venezuela',
  zw: 'Zimbabwe',
}

// countries supported by shuftipro KYB
export const KYB_COUNTRY_CODES = {
  ae_az: 'Abu Dhabi (UAE)',
  al: 'Albania',
  aw: 'Aruba',
  au: 'Australia',
  bs: 'Bahamas',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  bb: 'Barbados',
  by: 'Belarus',
  be: 'Belgium',
  bz: 'Belize',
  bm: 'Bermuda',
  bo: 'Bolivia',
  br: 'Brazil',
  bg: 'Bulgaria',
  kh: 'Cambodia',
  ca: 'Canada',
  hr: 'Croatia',
  cw: 'Curaçao',
  cy: 'Cyprus',
  dk: 'Denmark',
  do: 'Dominican Republic',
  ae_du: 'Dubai (UAE)',
  fi: 'Finland',
  fr: 'France',
  gf: 'French Guiana',
  de: 'Germany',
  gi: 'Gibraltar',
  gr: 'Greece',
  gl: 'Greenland',
  gp: 'Guadeloupe',
  gg: 'Guernsey',
  hk: 'Hong Kong',
  is: 'Iceland',
  in: 'India',
  ir: 'Iran',
  ie: 'Ireland',
  im: 'Isle of Man',
  il: 'Israel',
  jm: 'Jamaica',
  jp: 'Japan',
  je: 'Jersey',
  lv: 'Latvia',
  li: 'Liechtenstein',
  lu: 'Luxembourg',
  my: 'Malaysia',
  mt: 'Malta',
  mq: 'Martinique',
  mu: 'Mauritius',
  yt: 'Mayotte',
  mx: 'Mexico',
  md: 'Moldova',
  me: 'Montenegro',
  mm: 'Myanmar',
  nl: 'Netherlands',
  nz: 'New Zealand',
  no: 'Norway',
  pk: 'Pakistan',
  pa: 'Panama',
  pl: 'Poland',
  pr: 'Puerto Rico',
  ro: 'Romania',
  rw: 'Rwanda',
  re: 'Réunion',
  bl: 'Saint Barthélemy',
  mf: 'Saint Martin (French part)',
  pm: 'Saint Pierre and Miquelon',
  sg: 'Singapore',
  sk: 'Slovakia',
  si: 'Slovenia',
  za: 'South Africa',
  es: 'Spain',
  se: 'Sweden',
  ch: 'Switzerland',
  tj: 'Tajikistan',
  tz: 'Tanzania',
  th: 'Thailand',
  to: 'Tonga',
  tn: 'Tunisia',
  ug: 'Uganda',
  ua: 'Ukraine',
  gb: 'United Kingdom',
  us: 'United States',
  vu: 'Vanuatu',
  vn: 'Viet Nam',
}
