name: Deploy Catalyst
on:
  push:
    tags:
      - "centrifuge-app/v*"
concurrency:
 # Cancel any staging or prod deployment on-going
 # in favor of this new pre-release
  group: catalyst-deployment
  cancel-in-progress: true 
  
jobs:
  app-staging:
    uses: ./.github/workflows/centrifuge-app.yml
    secrets: inherit
    with:
      deploy_env: catalyst


  pinning-staging:
    uses: ./.github/workflows/pinning-api.yml
    secrets: inherit
    with:
      deploy_env: catalyst


  onboarding-staging:
    uses: ./.github/workflows/onboarding-api.yml
    secrets: inherit
    with:
      deploy_env: catalyst