name: 'centrifuge-js publish'
on:
  push:
    tags:
      - centrifuge-js/v*

defaults:
  run:
    working-directory: centrifuge-js

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint

      # - name: Tests
      #   run: yarn test

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
