# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Centrifuge App
on:
  pull_request:
    paths-ignore:
      - 'centrifuge-app/**'
      - 'centrifuge-js/**'
      - 'centrifuge-react/**'
      - '.github/workflows/centrifuge-app.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'      