name: Deploy Gfunction
on:
  push:
    branches:
      - main
    tags:
      - "rc*"
    paths:
      - 'centrifuge-app/**'
      - '.github/workflows/centrifuge-app.yml'
  pull_request:
    paths:
      - 'centrifuge-app/**'
      - '.github/workflows/centrifuge-app.yml'
  workflow_call:
    inputs:
      deploy_env:
        type: string
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: cent-functions-${{ github.ref }}
      cancel-in-progress: true   
    defaults:
      run:
        working-directory: centrifuge-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare env logic
        id: prepare
        uses: ./.github/actions/deployment_strategy
        with:
          app_base_name: app
          deploy_to: ${{ inputs.deploy_env }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint

      - name: Build centrifuge-app
        env:
          config_file: ./centrifuge-app/env-config/${{ matrix.deploy_env}}
        run: |
          cat .env-conf/${{ steps.prepare.outputs.env_name }}
          vite build -mode ${{ steps.prepare.outputs.env_name }}
      
      - uses: actions/upload-artifact@v3
        with: 
          name: webpack
          path: ./centrifuge-app/build
          if-no-files-found: error
    outputs:
      front_url: ${{ steps.prepare.outputs.front_url }}

  deployment:
    concurrency:
      group: cent-functions-${{ github.ref }}
      cancel-in-progress: true    
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_call' && production || development }}
    # Note: environment = production requires additional approvals, it only happen on manual trigger to the main branch
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      region: europe-central2
    steps:
      - name: deploy to GCS
        id: functionsdeploy
        uses: ./.github/actions/deploy-gcs
        with:
          artifact_name: webpack 
          bucket_url: ${{ needs.build.front_url }}
          GWIP: ${{ secrets.GWIP }}
          GSA: ${{ secrets.GSA }}

