name: 'tinlake-ui Update changelog'
on:
  push:
    branches:
      - main
    paths:
      - 'tinlake-ui/**'
      - '.github/workflows/changelog-generator.yml'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install gem
        run: gem install github_changelog_generator

      - name: Run changelog generator
        timeout-minutes: 10 # when GH API rate is exceeded, the generator hangs. Abort changelog generation in this case
        run: github_changelog_generator -u centrifuge -p apps --since-tag tinlake-ui/release-30 -t ${{ secrets.GITHUB_TOKEN }}

      - name: check for changes
        run: git status

      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name "changelog-generator"
          git add .
          git commit -m "chore: update changelog"

      - name: fetch from main
        run: git fetch origin main

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: changelog
          force: true
