name: Delete lingering functions and buckets

on:
  pull_request:
    types:
      - "closed"

jobs:
  cleanup-pr:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    environment: preview
    steps:
      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # v1.0.1     
      - name: Delete function
        run: gcloud functions delete ${{env.app_name}} --region=${{ env.region }}
      
      - name: remove gcs buckets
        run: gcloud storage rm --recursive gs://${{ inputs.app_base_name }}-pr${{ github.event.number }}.k-f.co