name: dev-n-ffprod-deploys
on:
  push:
    branches: main
  pull_request:
    # paths:
    #   - '.github/workflows/main-branch-deploys.yml'
  
jobs:
  main_branch:
    if: github.ref == 'refs/heads/main'
    name: deploy-${{ matrix.env }}
    strategy:
      matrix:
        env: ['ff-prod', 'development']
    uses: ./.github/workflows/deploy_all.yml
    secrets: inherit
    with:
      environment: ${{ matrix.env }}

  pull_request:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy_all.yml
    secrets: inherit
    with:
      environment: 'ff-prod'