name: 'Fabric'
on:
  push:
    branches:
      - main
    paths:
      - 'fabric/**' # dependency
      - '.github/workflows/fabric-test.yml'

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fabric

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build Fabric components
        run: yarn build

      - name: Run Visual regression tests
        run: yarn ci:loki