name: Fabric and storybook
on:
  push:
    branches:
      - main
    paths:
      - 'fabric/**'
      - '.github/workflows/fabric.yml'
  pull_request:
    paths:
      - '.github/workflows/fabric.yml'
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build-fabric:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fabric

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #@v4.4.0
        with:
          node-version: '20'
          cache: yarn

      - run: yarn install --immutable
      - run: yarn build

      - name: Build fabric storybook
        run: yarn build-storybook

      - name: Archive storybook artifacts
        # if: github.ref === 'refs/heads/main'
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # @v4.6.0
        with:
          name: fabric-storybook
          retention-days: 1
          path: ./fabric/storybook-static

  deploy-storybook: # to google storage
    # if: github.ref == 'refs/heads/main'
    needs: build-fabric
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: apps

      - name: deploy to GCS
        id: gcsdeploy
        uses: ./apps/.github/actions/deploy-gcs
        with:
          artifact_name: fabric-storybook
          bucket_url: 'fabric-storybook.k-f.dev'
          GWIP: ${{ secrets.GWIP }}
          GSA: ${{ secrets.GSA }}

  # ToDo: send notification when deployed?
