name: 'Fabric'
on:
  push:
    branches:
      - main
    paths:
      - 'fabric/**' 
      - '.github/workflows/fabric.yml'

jobs:
  build-n-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fabric

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: yarn ci:loki

      - name: Build fabric storybook
        run: yarn build-storybook

      - name: Archive storybook artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # @v3.1.2
        with:
          name: onboarding-api
          retention-days: 1
          path: ./fabric/storybook-static


  deploy-storybook: # too google storage
        