name: Fabric and storybook
on:
  push:
    branches:
      - main
    paths:
      - 'fabric/**' 
      - '.github/workflows/fabric.yml'

jobs:
  build-n-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fabric

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - run: yarn install # --immutable
      - run: yarn build
      - run: yarn ci:loki

      - name: Build fabric storybook
        run: yarn build-storybook

      - name: Archive storybook artifacts
        if: github.ref === 'refs/heads/main'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # @v3.1.2
        with:
          name: fabric-storybook
          retention-days: 1
          path: ./fabric/storybook-static


  deploy-storybook: # to google storage
    if: github.ref === 'refs/heads/main'
    needs: build-n-test
    permissions:
      contents: 'read'
      id-token: 'write'  
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: deploy to GCS
        id: gcsdeploy
        uses: ./.github/actions/deploy-gcs
        with:
          artifact_name: fabric-storybook
          bucket_url: 'fabric-storybook.k-f.dev'
          GWIP: ${{ secrets.GWIP }}
          GSA: ${{ secrets.GSA }}
  
  # ToDo: send notification when deployed?