name: deploy-main
on:
  push:
    branches: main
  pull_request:
    paths:
      - '.github/workflows/main-branch-deploys.yml'
  
jobs:
  trigger:
    name: deploy-${{ matrix.env }}
    strategy:
      matrix:
        env: ['ff-prod', 'development']
    uses: ./.github/workflows/deploy_all.yml
    secrets: inherit
    with:
      environment: ${{ matrix.env }}