name: 'nft-studio PROD'
on:
  push:
    tags:
      - nft-studio/release-*

jobs:
  dev:
    uses: centrifuge/apps/.github/workflows/nft-studio-build-and-deploy.yml@main
    with:
      netlify-alias: ''
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      netlify-site-id: ${{ secrets.NFT_STUDIO_PROD_NETLIFY_SITE_ID }}
