name: 'onboarding-app Deploy to Staging'
on:
  push:
    branches:
      - rc/onboarding-app/release-*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: onboarding-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install

      - name: Cache Next.js Bundle
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/onboarding-app/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: yarn export
        env:
          NEXT_PUBLIC_CENTRIFUGE_CHAIN_URL: 'wss://fullnode.parachain.centrifuge.io'
          NEXT_PUBLIC_CLAIM_CFG_CONTRACT_ADDRESS: '0x1cA3B2E7FfCAF83d9228a64e4726402B1d5CC054'
          NEXT_PUBLIC_ENV: 'PROD'
          NEXT_PUBLIC_ETHERSCAN_URL: 'https://etherscan.io'
          NEXT_PUBLIC_FEATURE_FLAG_NEW_ONBOARDING: '0x4B6CA198d257D755A5275648D471FE09931b764A,0xdB3bC9fB1893222d266762e9fF857EB74D75c7D6,0xfc2950dD337ca8496C18dfc0256Fb905A7E7E5c6,0x53b2d22d07E069a3b132BfeaaD275b10273d381E,0x0CED6166873038Ac0cc688e7E6d19E2cBE251Bf0,0x4cA805cE8EcE2E63FfC1F9f8F2731D3F48DF89Df,0x82B8617A16e388256617FeBBa1826093401a3fE5,0x560Ac248ce28972083B718778EEb0dbC2DE55740,0x3d167bd08f762FD391694c67B5e6aF0868c45538,0x3B03863BD553C4CE07eABF2278016533451c9101,0x09e43329552c9D81cF205Fd5f44796fBC40c822e,0xF96F18F2c70b57Ec864cC0C8b828450b82Ff63e3,0xd8486C565098360A24f858088a6D29a380dDF7ec'
          NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
          NEXT_PUBLIC_IPFS_GATEWAY: 'https://cloudflare-ipfs.com/ipfs/'
          NEXT_PUBLIC_MULTICALL_CONTRACT_ADDRESS: '0xeefba1e63905ef1d7acba5a8513c70307c1ce441'
          NEXT_PUBLIC_ONBOARD_API_HOST: 'https://onboard-api.centrifuge.io/'
          NEXT_PUBLIC_RWA_MARKET_ONBOARD_RETURN_URL: 'https://rwamarket.io'
          NEXT_PUBLIC_TINLAKE_ONBOARD_RETURN_URL: 'https://tinlake.centrifuge.io'
          NEXT_PUBLIC_POOL_REGISTRY: '0xddf1c516cf87126c6c610b52fd8d609e67fb6033'
          NEXT_PUBLIC_POOLS_IPFS_HASH_OVERRIDE: 'QmNQgifPwYUXqpsyd2j3hG2piiYkoYZoUSYC8Tcq1YWYEz'
          NEXT_PUBLIC_PORTIS_KEY: 'bc9e2922-2ebd-4e2b-86f6-7c7855bdf07f'
          NEXT_PUBLIC_REWARDS_TREE_URL: 'https://storage.googleapis.com/rad-rewards-trees-mainnet-production/latest.json'
          NEXT_PUBLIC_RPC_URL: 'https://mainnet.infura.io/v3/ed5e0e19bcbc427cbf8f661736d44516'
          NEXT_PUBLIC_TINLAKE_DATA_BACKEND_URL: 'https://api.thegraph.com/subgraphs/name/centrifuge/tinlake'
          NEXT_PUBLIC_TRANSACTION_TIMEOUT: '3600'

      - name: Deploy To Netlify
        uses: nwtgck/actions-netlify@v1.2.0
        with:
          deploy-message: ${{ github.event.head_commit.message }}
          enable-commit-comment: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./onboarding-app/netlify.toml
          production-deploy: true
          publish-dir: ./onboarding-app/out
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN  }}
          NETLIFY_SITE_ID: ${{ secrets.ONBOARDING_STAGING_NETLIFY_SITE_ID }}
