# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Pinning API 
on:
  pull_request:
    paths-ignore:
      - 'pinning-api/**'
      - '.github/workflows/pinning-api.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'      