name: Promote staging to PROD
on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      tag:
        description: 'The release tag to promote (e.g. v1.2.3) do not append centrifuge-app to the tag'
        required: true
        type: string
concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy-app:
    name: app-prod-deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: apps
          sparse-checkout: |
            .github/actions/prepare-deploy

      - name: prepare env logic
        id: prepare
        uses: ./apps/.github/actions/prepare-deploy
        with:
          app_base_name: app
          deploy_to: 'production'

      - name: Auth gcloud
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2

      - uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # v1.1.2
        with:
          repo: 'centrifuge/apps'
          version: ${{ github.event_name == 'release' && github.event.release.id || format('tags/centrifuge-app/{0}', inputs.tag) }}
          file: "webpack.zip"
          regex: true

      - name: Unzip release files
        run: |
          unzip webpack.zip -d webpack 1> /dev/null

      - name: Sync webpack from staging
        run: gsutil -m rsync -d -r ./webpack/ gs://${{ steps.prepare.outputs.front_url }}

  deploy-functions:
    name: ${{ matrix.function.name }}-prod-deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        function:
          - name: pinning-api
            handler: pinningApi
            service_account: ${{ vars.PINNING_API_FUNCT_SA }}
          - name: onboarding-api
            handler: onboarding
            service_account: ${{ vars.ONBOARDING_FUNCT_SA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: apps
          sparse-checkout: |
            .github/actions/deploy-gfunction

      - uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # v1.1.2
        with:
          repo: 'centrifuge/apps'
          version: ${{ github.event_name == 'release' && github.event.release.id || format('tags/centrifuge-app/{0}', inputs.tag) }}
          file: "${{ matrix.function.name }}.zip"
          regex: true

      - name: Unzip release files
        run: |
          unzip ${{ matrix.function.name }}.zip -d ${{ matrix.function.name }} 1> /dev/null

      - name: Deploy Gfunction
        id: functionsdeploy
        uses: ./apps/.github/actions/deploy-gfunction
        with:
          app_name: ${{ matrix.function.name }}
          GWIP: ${{ secrets.GWIP }}
          GSA: ${{ secrets.GSA }}
          target: ${{ matrix.function.handler }}
          gcloud_region: ${{ vars.GCLOUD_REGION }}
          service_account: '${{ matrix.function.service_account }}'
          deploy_env: production

  slack-notify-success:
    needs: [deploy-app, deploy-functions]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Notify prod deploy success
        uses: rtCamp/action-slack-notify@c33737706dea87cd7784c687dadc9adf1be59990 # v2.3.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            ✅ Production deployment successful!
            app.staging.centrifuge.io has been promoted to app.centrifuge.io and is now LIVE!
            Check out the new release -> https://github.com/centrifuge/apps/releases/
          SLACK_USERNAME: 'Centrifuge GHA Bot'
          SLACK_ICON: 'https://centrifuge.io/favicon.ico'
          SLACK_TITLE: 'Centrifuge app has been promoted to prod.'
          SLACK_FOOTER: 'Automatic message from centrifuge/apps repository Actions'
          MSG_MINIMAL: true
          SLACK_COLOR: 'good'

  slack-notify-failure:
    needs: [deploy-app, deploy-functions]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify prod deploy failure
        uses: rtCamp/action-slack-notify@c33737706dea87cd7784c687dadc9adf1be59990 # v2.3.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            ❌ Production deployment failed!
            One or more jobs failed during the promotion to production.
            Please check the workflow run for details -> ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_USERNAME: 'Centrifuge GHA Bot'
          SLACK_ICON: 'https://centrifuge.io/favicon.ico'
          SLACK_TITLE: '⚠️ Production Deployment Failed'
          SLACK_FOOTER: 'Automatic message from centrifuge/apps repository Actions'
          MSG_MINIMAL: true
          SLACK_COLOR: 'danger'
