name: Deploy Prod
on:
  release:
    types:
      - released     
  workflow_dispatch:

jobs:
  sync_staging_prod:
    runs-on: ubuntu-latest
    environment: production
    steps:   
      - name: Auth gcloud
        id: gauth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # @v1
        with:
          workload_identity_provider: '${{ secrets.GWIP }}'
          service_account: '${{ secrets.GSA }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587 # @v1 

      - name: Sync webpack from staging
        run: gsutil -m rsync -d -r gs://app-staging.centrifuge.io gs://app.centrifuge.io
  
  retrieve_release_assets:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:  
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'centrifuge/apps'
          version: 'tags/${{ github.ref_name }}'
          file: '*.zip'
          # target: 'subdir/${{ matrix.artifact_name }}.zip'
          # token: ${{ secrets.GITHUB_TOKEN }}
      
      - run: ls -la

      - name: Unzip release files
        run: |
          unzip pinning-api.zip -d pinning-api 1> /dev/null
          unzip onboarding-api.zip -d onboarding-api 1> /dev/null

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce #@3.1.2
        with: 
          name: onboading-api
          path: ./onboading-api
          if-no-files-found: error 
          
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce #@3.1.2
        with: 
          name: pinning-api
          path: ./pinning-api
          if-no-files-found: error 

  deploy_pinning:
    needs: retrieve_release_assets
    uses: ./.github/workflows/pinning-api.yml
    secrets: inherit
    with:
      deploy_env: production
      artifact_name: pinning-api


  deploy_onboarding:
    needs: retrieve_release_assets
    uses: ./.github/workflows/onboarding-api.yml
    secrets: inherit
    with:
      deploy_env: production
      artifact-name: onboarding-api
    