name: 'tinlake-ui'
on: 
  push:
    branches:
      - main
  pull_request:
    paths:
    - 'tinlake-ui/**'

defaults:
  run:
    working-directory: tinlake-ui

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install
      - run: yarn lint
      - run: yarn check-format
      - run: yarn lint
      - run: yarn export
      - run: yarn lint
            
    env:
      NEXT_PUBLIC_PORTIS_KEY: "bc9e2922-2ebd-4e2b-86f6-7c7855bdf07f"
      NEXT_PUBLIC_ETHERSCAN_URL: "https://kovan.etherscan.io"
      NEXT_PUBLIC_RPC_URL: "https://kovan.infura.io/v3/092108ec6aea46ab97b2175b45130455"
      NEXT_PUBLIC_ENV: "demo"
      NEXT_PUBLIC_TRANSACTION_TIMEOUT: "3600"
      NEXT_PUBLIC_TINLAKE_DATA_BACKEND_URL: "https://api.thegraph.com/subgraphs/name/centrifuge/tinlake-kovan-staging"
      NEXT_PUBLIC_POOLS_CONFIG: "kovanStaging"