name: 'tinlake-ui Deploy to Prod'
on:
  push:
    tags:
      - tinlake-ui/release-*
    paths:
      - 'tinlake-ui/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tinlake-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn export
        env:
          NEXT_PUBLIC_CENTRIFUGE_CHAIN_URL: 'wss://fullnode.centrifuge.io'
          NEXT_PUBLIC_CLAIM_CFG_CONTRACT_ADDRESS: '0x1cA3B2E7FfCAF83d9228a64e4726402B1d5CC054'
          NEXT_PUBLIC_ENV: 'PROD'
          NEXT_PUBLIC_ETHERSCAN_URL: 'https://etherscan.io'
          NEXT_PUBLIC_FEATURE_FLAG_NEW_ONBOARDING: '0x4B6CA198d257D755A5275648D471FE09931b764A'
          NEXT_PUBLIC_INFURA_KEY: ${{ secrets.NEXT_PUBLIC_INFURA_KEY }}
          NEXT_PUBLIC_IPFS_GATEWAY: 'https://cloudflare-ipfs.com/ipfs/'
          NEXT_PUBLIC_MULTICALL_CONTRACT_ADDRESS: '0xeefba1e63905ef1d7acba5a8513c70307c1ce441'
          NEXT_PUBLIC_ONBOARD_API_HOST: 'https://onboard-api.centrifuge.io/'
          NEXT_PUBLIC_POOL_REGISTRY: '0xddf1c516cf87126c6c610b52fd8d609e67fb6033'
          NEXT_PUBLIC_POOLS_CONFIG: 'mainnetProduction'
          NEXT_PUBLIC_POOLS_IPFS_HASH_OVERRIDE: 'QmcbcPFtR6Ey5ARwZwbAKEuFvHKP8sYStDCuEpqm52jTPu'
          NEXT_PUBLIC_PORTIS_KEY: 'bc9e2922-2ebd-4e2b-86f6-7c7855bdf07f'
          NEXT_PUBLIC_REWARDS_TREE_URL: 'https://storage.googleapis.com/rad-rewards-trees-mainnet-production/latest.json'
          NEXT_PUBLIC_RPC_URL: 'https://mainnet.infura.io/v3/ed5e0e19bcbc427cbf8f661736d44516'
          NEXT_PUBLIC_TINLAKE_DATA_BACKEND_URL: 'https://thegraph.centrifuge.io/subgraphs/name/centrifuge/tinlake'
          NEXT_PUBLIC_TRANSACTION_TIMEOUT: '3600'

      - name: Deploy To Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          deploy-message: ${{ github.event.head_commit.message }}
          enable-commit-comment: false
          functions-dir: 'functions'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./netlify.toml
          production-branch: production
          production-deploy: true
          publish-dir: 'out'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN  }}
          NETLIFY_SITE_ID: ${{ secrets.TINLAKE_UI_PROD_NETLIFY_SITE_ID }}
